name: Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add your Jekyll build and deploy steps here
      # For example:
      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          # Add your deployment steps here
